theme:
  default: style-dark
user:
  name: 湘江中路 # Nickname | 昵称
  first_name: 嘉鸿 # 名
  last_name: 陈 # 姓
  email: chenjiahong@datasega.com
  avatar: https://raw.githubusercontent.com/CPeace-creator/picGo/main/logo.jpg
  describe: 网站简介。 # Describe | 网站简介
  rule_text: 暂不接受个人博客以外的友链申请，确保您的网站内容积极向上，文章至少30篇，原创70%以上，部署HTTPS。 # 友链规则
favicon:
  logo: https://raw.githubusercontent.com/CPeace-creator/picGo/main/logo.jpg
  show_text: (/≧▽≦/)咦！又好了！
  hide_text: (●—●)喔哟，崩溃啦！
assets:
  third_party_provider: https://npm.elemecdn.com
footer:
  powered:
    enable: false
  beian:
    enable: true
    icp:
  copyright_year:
  live_time:
    enable: true
    prefix: footer.tips
    start_time: 03/01/2025 17:00:00
  custom_text: 制作不易,请留个言再离开吧～
top_bars:
  - title: 技术栈
    url: /2025/04/19/technology/index/
  - title: 关于我
    url: /2025/03/05/home/
  - title: 我的项目
    url: /
    children:
      - title: UniPush推送
        url: /2025/03/16/uniPush/
      - title: 课海导航
        url: /2025/03/23/courseSea/
      - title: 卡车物流系统
        url: /2025/03/23/EPR/
    noswup: true
sidebar:
  typed_text_prefix: I`m
  typed_text: ["Web Developer"]
  info: # 个人信息
    - key: 目标
      val: 独立开发
    - key: 2025目标
      val: 开发课海导航项目
banner:
  default: # 默认横幅配置
    type: img # 横幅类型 <[img,slideshow,video]>
    bgurl: https://raw.githubusercontent.com/CPeace-creator/picGo/main/fj1.jpg # 背景图地址
    banner_text: Hi my new friend! # 横幅描述
    position: top # 同 CSS object-position
    fit: cover # 同 CSS object-fit
  index: ## 首页横幅
    banner_title: 代码深时见梦,<br>夜半不闻声。
    banner_text: Hi my new friend!
	danmu:
		enable: true
		avatar: true
		delayRange: 5000
		speed: 80
